const data={Work:{"Running late":["Running late — joining soon","Running a bit late, will join soon","Running behind, almost there"]},Friend:{"Running late":["Running late bro","On the way"]},Client:{"Running late":["Apologies, running slightly late"]}};
let currentCategory=null;
document.addEventListener("DOMContentLoaded",()=>{renderCategories();});
function renderCategories(){const el=document.getElementById("categories");el.innerHTML=Object.keys(data).map(cat=>`<button onclick="selectCategory('${cat}',event)">${cat}</button>`).join('');}
function selectCategory(cat,e){currentCategory=cat;document.querySelectorAll("#categories button").forEach(btn=>btn.classList.remove("active"));e.target.classList.add("active");document.getElementById("situations").innerHTML=Object.keys(data[cat]).map(s=>`<button onclick="selectSituation('${s}',event)">${s}</button>`).join('');}
function selectSituation(s,e){document.querySelectorAll("#situations button").forEach(btn=>btn.classList.remove("active"));e.target.classList.add("active");const replies=data[currentCategory][s];document.getElementById("replies").innerHTML=replies.map(r=>`<div class="reply" onclick="copyText('${r}')">${r}</div>`).join('');document.getElementById("tryAnotherBtn").style.display="inline-block";}
function copyText(text){navigator.clipboard.writeText(text);const msg=document.getElementById("copiedMsg");msg.style.display="block";setTimeout(()=>msg.style.display="none",2000);}
function saveEmail(){const email=document.getElementById("email").value;const check=document.getElementById("notbot").checked;if(!check){alert("Confirm you're not a bot");return;}if(!email.includes("@")){alert("Enter valid email");return;}alert("Saved");}
function resetFlow(){document.getElementById("situations").innerHTML="";document.getElementById("replies").innerHTML="";document.querySelectorAll("button").forEach(btn=>btn.classList.remove("active"));document.getElementById("tryAnotherBtn").style.display="none";document.getElementById("email").value="";document.getElementById("notbot").checked=false;window.scrollTo({top:0,behavior:"smooth"});}
